project:
  type: website
  output-dir: docs
  
website:
  title: ""
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gfleetwood
format:
  html:
    theme: cosmo
    css: styles.css



